# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    before_all do
    gradle(task: "clean")
    end

    def date_string()
      Time.now.strftime("%m/%d/%Y")
    end

    desc "Build local released apk and send msg to @SlowLaneBot"
    lane :assemble_release do
    gradle(
        task: "assemble",
        build_type: "release"
    )

    telegram(
        token: "#$token",
        chat_id: "#$chatId",
        text: "Release zxing scan apk built on #{date_string()}."
    )
    end

    desc "Deploy a new version to the Google Play and send msg to @SlowLaneBot"
    lane :beta do
        gradle(
          task: "assemble",
          build_type: "release"
        )

        upload_to_play_store(track: 'beta')

        telegram(
          token: "#$token",
          chat_id: "#$chatId",
          text: "Beta zxing scan apk built on #{date_string()}."
        )
    end

    desc "Deploy a new version to the Google Play and send msg to @SlowLaneBot"
    lane :deploy do
        gradle(
            task: "assemble",
            build_type: "release"
        )

        upload_to_play_store

        telegram(
            token: "#$token",
            chat_id: "#$chatId",
            text: "Deploy zxing scan apk built on #{date_string()}."
        )
    end

    desc "Runs all the tests"
    lane :test do
      gradle(task: "test")
    end

end






