# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  before_all do
    gradle(task: "clean")
  end

  def date_string()
      Time.now.strftime("%m/%d/%Y")
  end

  desc "Build local released apk and send msg to @SlowLaneBot"
  lane :assemble_release do
    gradle(
        task: "assemble",
        build_type: "release"
    )

  	telegram(
        token: "token",
        chat_id: "chat id",
        text: "Zxing scan apk built on #{date_string()}."
    )
  end

  desc "Deploy a new version to the Google Play and send msg to @SlowLaneBot"
    lane :deploy do
        gradle(
            task: "assemble",
            build_type: "release"
        )

        upload_to_play_store

      	telegram(
            token: "token",
            chat_id: "chat id",
            text: "Zxing scan apk built on #{date_string()}."
        )
    end

  desc "Runs all the tests"
    lane :test do
      gradle(task: "test")
    end

    desc "Submit a new Beta Build to Crashlytics Beta"
    lane :beta do
      gradle(task: "clean assembleRelease")
      crashlytics

      # sh "your_script.sh"
      # You can also use other beta testing services here
    end

end






